# Generated by Django 4.1.7 on 2023-12-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist_playlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlists', to='music.song'),
        ),
        migrations.DeleteModel(
            name='Playlistitem',
        ),
    ]
