# Generated by Django 4.1.7 on 2023-12-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlist_songs_delete_playlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
