# Generated by Django 4.1.7 on 2023-12-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_playlist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='image',
        ),
    ]
